# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
index:
    path: /users
    controller: App\Controller\UserController::index